### ISSUE TITLE
error in parse_mreps_result

### ISSUE THREAD

**Issue by wdecoster** [collaborativebioinformatics/STRdust#38]
In a local test genome:

```
Traceback (most recent call last):
  File "/home/wdecoster/miniconda3/envs/strdust/bin/STRdust", line 33, in <module>
    sys.exit(load_entry_point('STRdust', 'console_scripts', 'STRdust')())
  File "/home/wdecoster/repositories/strdust/STRdust/STRdust.py", line 149, in main
    mreps_dict = parse_mreps_result(run_mreps(ins_chr_file, args.mreps_res))
  File "/home/wdecoster/repositories/strdust/STRdust/STRdust.py", line 360, in parse_mreps_result
    all_repeat_info = [list(g) for k, g in groupby(
IndexError: list index out of range
```

**Comment by wdecoster** [comment]
For this particular case `output_list` is [" 'chr15_17003213_17003238'", '', '* Processing window [1 : 0] *', '', 'Processed sequence is too short', '', '']
